# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BookClub' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookClub
  
  # Required by RNFirebase
  pod 'Firebase/Core'
  
  pod 'AppCenter/Crashes', '~> 1.4.0'
  pod 'AppCenter/Analytics', '~> 1.4.0'
  pod 'AppCenterReactNativeShared', '~> 1.3.0'

  

  platform :ios, '9.0'
  target 'BookClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BookClub-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookClub-tvOS

  target 'BookClub-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
